import RecognitionPaths.ExtensionalCollapse

/-!
# Biextensional collapse of an observation system

`ExtensionalCollapse.lean` quotients the states of an observation system by
equality of their test profiles.  The dual operation quotients the tests by
equality of their state profiles: two tests that return the same output on
every state are the same test.  Doing both gives the *biextensional
collapse* of the Chu space (states, tests, observe): a system in which the
tests separate the states and the states separate the tests.

For a Hankel table this is exactly "distinct rows × distinct columns".
The counts reported in Phase 3.2 (`proof-path-invariance`) are the sizes
of the two quotients constructed here.
-/

namespace RecognitionPaths

universe u v w

namespace ObservationSystem

variable {Test : Type v} {Output : Type w}

/-- The profile of a test across all states. -/
def coprofile (A : ObservationSystem.{u, v, w} Test Output) : Test → A.State → Output :=
  fun t s => A.observe s t

/-- Two tests are observationally identical when every state answers them
    alike. -/
def testSetoid (A : ObservationSystem.{u, v, w} Test Output) : Setoid Test where
  r t t' := A.coprofile t = A.coprofile t'
  iseqv := ⟨fun _ => rfl, fun h => h.symm, fun h₁ h₂ => h₁.trans h₂⟩

/-- The test space generated by the states. -/
abbrev TestCollapse (A : ObservationSystem.{u, v, w} Test Output) :=
  Quotient A.testSetoid

/-- A system is coextensional when its states separate its tests. -/
def Coextensional (A : ObservationSystem.{u, v, w} Test Output) : Prop :=
  Function.Injective A.coprofile

/-- The biextensional collapse: states modulo their test profiles, tests
    modulo their state profiles, observation inherited from any
    representatives. -/
def biextensionalCollapse (A : ObservationSystem.{u, v, w} Test Output) :
    ObservationSystem.{u, v, w} A.TestCollapse Output where
  State := A.Collapse
  observe := Quotient.lift₂ (fun s t => A.observe s t)
    (fun s t s' t' hs ht => by
      have h1 : A.observe s t = A.observe s' t := congrFun hs t
      have h2 : A.observe s' t = A.observe s' t' := congrFun ht s'
      exact h1.trans h2)

@[simp]
theorem biextensionalCollapse_observe_mk (A : ObservationSystem.{u, v, w} Test Output)
    (s : A.State) (t : Test) :
    A.biextensionalCollapse.observe (Quotient.mk A.observationalSetoid s)
      (Quotient.mk A.testSetoid t) = A.observe s t :=
  rfl

/-- In the biextensional collapse, tests separate states. -/
theorem biextensionalCollapse_extensional (A : ObservationSystem.{u, v, w} Test Output) :
    A.biextensionalCollapse.Extensional := by
  intro q₁ q₂
  refine Quotient.inductionOn₂ q₁ q₂ ?_
  intro s₁ s₂ h
  apply Quotient.sound
  funext t
  exact congrFun h (Quotient.mk A.testSetoid t)

/-- In the biextensional collapse, states separate tests. -/
theorem biextensionalCollapse_coextensional (A : ObservationSystem.{u, v, w} Test Output) :
    A.biextensionalCollapse.Coextensional := by
  intro q₁ q₂
  refine Quotient.inductionOn₂ q₁ q₂ ?_
  intro t₁ t₂ h
  apply Quotient.sound
  funext s
  exact congrFun h (Quotient.mk A.observationalSetoid s)

/-- Collapsing the tests does not change the state quotient: the state
    collapse of the biextensional collapse is the state collapse of `A`.
    (Stated as: two states have equal profiles in `A` iff their classes have
    equal profiles in the biextensional collapse.) -/
theorem profile_eq_iff_biext (A : ObservationSystem.{u, v, w} Test Output) (s₁ s₂ : A.State) :
    A.profile s₁ = A.profile s₂ ↔
      A.biextensionalCollapse.profile (Quotient.mk A.observationalSetoid s₁) =
        A.biextensionalCollapse.profile (Quotient.mk A.observationalSetoid s₂) := by
  constructor
  · intro h
    funext q
    refine Quotient.inductionOn q ?_
    intro t
    exact congrFun h t
  · intro h
    funext t
    exact congrFun h (Quotient.mk A.testSetoid t)

/-- A silent extension has the same test collapse: adding hidden state
    coordinates does not create or merge tests. -/
def testCollapseSilentEquiv (A : ObservationSystem.{u, v, w} Test Output) :
    A.silentExtension.TestCollapse ≃ A.TestCollapse where
  toFun := Quotient.lift (fun t => Quotient.mk A.testSetoid t)
    (fun t t' h => Quotient.sound (by
      funext s
      exact congrFun h (s, false)))
  invFun := Quotient.lift (fun t => Quotient.mk A.silentExtension.testSetoid t)
    (fun t t' h => Quotient.sound (by
      funext sb
      exact congrFun h sb.1))
  left_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro t
    rfl
  right_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro t
    rfl

end ObservationSystem

end RecognitionPaths
