import RecognitionPaths.ObservationalNonidentifiability
import RecognitionPaths.Equiv

namespace RecognitionPaths

universe u v w z

namespace ObservationSystem

/-- Two states are observationally identical when every chosen test returns
    the same output on them. -/
def observationalSetoid {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) : Setoid A.State where
  r x y := A.profile x = A.profile y
  iseqv := ⟨fun _ => rfl, fun h => h.symm, fun h₁ h₂ => h₁.trans h₂⟩

/-- The state space generated by observations, rather than postulated behind
    them. -/
abbrev Collapse {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) :=
  Quotient A.observationalSetoid

/-- A state of the collapse is observed through any representative. -/
def collapseProfile {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) :
    A.Collapse → Test → Output :=
  Quotient.lift A.profile fun _ _ h => h

/-- The canonical extensional realization generated by an observation
    system. -/
def extensionalCollapse {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) :
    ObservationSystem.{u, v, w} Test Output where
  State := A.Collapse
  observe := A.collapseProfile

@[simp]
theorem collapseProfile_mk {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) (s : A.State) :
    A.collapseProfile (Quotient.mk A.observationalSetoid s) = A.profile s :=
  rfl

/-- By construction, the collapsed tests separate all collapsed states. -/
theorem extensionalCollapse_is_extensional {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) :
    A.extensionalCollapse.Extensional := by
  intro q₁ q₂
  refine Quotient.inductionOn₂ q₁ q₂ ?_
  intro s₁ s₂ h
  exact Quotient.sound h

/-- Any state map constant on observational classes factors through the
    observation-generated collapse. -/
def collapseLift {Test : Type v} {Output : Type w} {Y : Type z}
    (A : ObservationSystem.{u, v, w} Test Output)
    (f : A.State → Y)
    (hf : ∀ ⦃x y⦄, A.profile x = A.profile y → f x = f y) :
    A.Collapse → Y :=
  Quotient.lift f fun _ _ h => hf h

@[simp]
theorem collapseLift_mk {Test : Type v} {Output : Type w} {Y : Type z}
    (A : ObservationSystem.{u, v, w} Test Output)
    (f : A.State → Y)
    (hf : ∀ ⦃x y⦄, A.profile x = A.profile y → f x = f y)
    (s : A.State) :
    A.collapseLift f hf (Quotient.mk A.observationalSetoid s) = f s :=
  rfl

/-- The factorization through the collapse is unique. -/
theorem collapseLift_unique {Test : Type v} {Output : Type w} {Y : Type z}
    (A : ObservationSystem.{u, v, w} Test Output)
    (f : A.State → Y)
    (hf : ∀ ⦃x y⦄, A.profile x = A.profile y → f x = f y)
    (g : A.Collapse → Y)
    (hg : ∀ s, g (Quotient.mk A.observationalSetoid s) = f s) :
    g = A.collapseLift f hf := by
  funext q
  refine Quotient.inductionOn q ?_
  intro s
  exact hg s

/-- Adding an observationally silent coordinate does not change the
    observation-generated state space. -/
def collapseSilentEquiv {Test : Type v} {Output : Type w}
    (A : ObservationSystem.{u, v, w} Test Output) :
    A.silentExtension.Collapse ≃ A.Collapse where
  toFun := Quotient.lift
    (fun sb => Quotient.mk A.observationalSetoid sb.1)
    (fun _ _ h => Quotient.sound h)
  invFun := Quotient.lift
    (fun s => Quotient.mk A.silentExtension.observationalSetoid (s, false))
    (fun _ _ h => Quotient.sound h)
  left_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro sb
    exact Quotient.sound rfl
  right_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro s
    rfl

end ObservationSystem

end RecognitionPaths
